language: python
notifications:
 email:
  - sdksupport@vantiv.com
env:
 global:
  - BUILD_DIR=`pwd`
  - CNP_CHARGEBACK_SDK_CONFIG=$BUILD_DIR
  - CHARGEBACK_CONFIG_FILE=$CNP_CHARGEBACK_SDK_CONFIG/.cnp_chargeback_sdk.conf
install:
 - pip install
 - python setup.py install
 - pip install coverage
script:
 - echo $BUILD_DIR
 - echo $CHARGEBACK_CONFIG_FILE
 - cat $CHARGEBACK_CONFIG_FILE
 - nosetests --with-coverage --with-xunit --verbosity=3 $BUILD_DIR/tests/unit $BUILD_DIR/tests/functional
after_success:
 - bash <(curl -s https://codecov.io/bash)
